version: '3'
services:
  web:
    platform: linux/amd64
    image: nginx:1.21
    container_name: docker-compose-mailhog-web
    build: ./web
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
  app:
    platform: linux/amd64
    build: ./php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
  db:
    platform: linux/amd64
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
  
    # mailhogの設定を追記
  mailhog:
    container_name: docker-compose-mailhog-mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
