FROM mysql:8.0
RUN apt-get update && apt-get -y install locales-all

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV MYSQL_DATABASE mysql
ENV MYSQL_USER team2D
ENV MYSQL_PASSWORD password
ENV MYSQL_ROOT_PASSWORD password
ENV TZ 'Asia/Tokyo'